[tasks.build-all]
description = "Build both Bcrush and BX12"
script = [
    "echo Building Bcrush...",
    "cd bcrush",
    "cargo build",
    "cd ..",
    "echo Building BX12...",
    "cd bx12",
    "cargo build",
]
[workspace]
members = [
    "bcrush",
    "bx12"
]