[tasks.build-bcrush]
description = "Build Bcrush core library"
command = "cargo"
args = ["build", "--release", "--manifest-path", "bcrush/Cargo.toml"]

[tasks.build-bx12]
description = "Build Bcrush-BX12 wrapper library"
command = "cargo"
args = ["build", "--release", "--manifest-path", "Bcrush-BX12/Cargo.toml"]

[tasks.build-all]
description = "Build both libraries"
dependencies = ["build-bcrush", "build-bx12"]
